//Projeto
export const ADICIONA_PROJETO = 'ADICIONA_PROJETO'
export const ALTERA_PROJETO = 'ALTERA_PROJETO'
export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO'
//Tarefa
export const ADICIONA_TAREFA = 'ADICIONA_TAREFA'
export const ATUALIZA_TAREFA = 'ATUALIZA_TAREFA'
export const REMOVE_TAREFA = 'REMOVE_TAREFA'
//Notificacao
export const NOTIFICAR = 'NOTIFICAR'